"""initial schema

Revision ID: f44cfb8da620
Revises:
Create Date: 2026-02-22 19:05:22.773696

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f44cfb8da620"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("parent_id", "name", name="uq_categories_parent_id_name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("name", name=op.f("uq_vendors_name")),
        sa.UniqueConstraint("short_name", name=op.f("uq_vendors_short_name")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("account_number_last4", sa.String(length=4), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_accounts_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_accounts_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_accounts_vendor_id"), ["vendor_id"], unique=False
        )

    op.create_table(
        "analysis_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_analysis_periods_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_periods")),
        sa.UniqueConstraint("user_id", "name", name="uq_analysis_periods_user_id_name"),
    )
    with op.batch_alter_table("analysis_periods", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_periods_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "budgeted_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payee", sa.String(length=200), nullable=False),
        sa.Column("variability", sa.String(length=20), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("date_scheduled", sa.Date(), nullable=False),
        sa.Column("budgeted_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_budgeted_expenses_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["categories.id"],
            name=op.f("fk_budgeted_expenses_subcategory_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_budgeted_expenses_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgeted_expenses")),
    )
    with op.batch_alter_table("budgeted_expenses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budgeted_expenses_category_id"),
            ["category_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_budgeted_expenses_date_scheduled"),
            ["date_scheduled"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_budgeted_expenses_payee"), ["payee"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budgeted_expenses_subcategory_id"),
            ["subcategory_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_budgeted_expenses_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "expense_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("budgeted_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("actual_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("variance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transaction_count", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_expense_analysis_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["analysis_periods.id"],
            name=op.f("fk_expense_analysis_period_id_analysis_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["categories.id"],
            name=op.f("fk_expense_analysis_subcategory_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_expense_analysis_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_analysis")),
        sa.UniqueConstraint(
            "period_id",
            "user_id",
            "category_id",
            "subcategory_id",
            name="uq_expense_analysis_period_user_category_subcategory",
        ),
    )
    with op.batch_alter_table("expense_analysis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expense_analysis_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expense_analysis_period_id"), ["period_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expense_analysis_subcategory_id"),
            ["subcategory_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_expense_analysis_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("post_date", sa.Date(), nullable=True),
        sa.Column("payee", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("debit_account_id", sa.Integer(), nullable=True),
        sa.Column("credit_account_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("subcategory_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["credit_account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_credit_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["debit_account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_debit_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["subcategory_id"],
            ["categories.id"],
            name=op.f("fk_transactions_subcategory_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_transactions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transactions_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_credit_account_id"),
            ["credit_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_debit_account_id"),
            ["debit_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_payee"), ["payee"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_subcategory_id"),
            ["subcategory_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_transaction_date"),
            ["transaction_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_transactions_user_id_transaction_date",
            ["user_id", "transaction_date"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_user_id_transaction_date")
        batch_op.drop_index(batch_op.f("ix_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_transaction_date"))
        batch_op.drop_index(batch_op.f("ix_transactions_subcategory_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_payee"))
        batch_op.drop_index(batch_op.f("ix_transactions_debit_account_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_credit_account_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_category_id"))

    op.drop_table("transactions")
    with op.batch_alter_table("expense_analysis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_analysis_user_id"))
        batch_op.drop_index(batch_op.f("ix_expense_analysis_subcategory_id"))
        batch_op.drop_index(batch_op.f("ix_expense_analysis_period_id"))
        batch_op.drop_index(batch_op.f("ix_expense_analysis_category_id"))

    op.drop_table("expense_analysis")
    with op.batch_alter_table("budgeted_expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budgeted_expenses_user_id"))
        batch_op.drop_index(batch_op.f("ix_budgeted_expenses_subcategory_id"))
        batch_op.drop_index(batch_op.f("ix_budgeted_expenses_payee"))
        batch_op.drop_index(batch_op.f("ix_budgeted_expenses_date_scheduled"))
        batch_op.drop_index(batch_op.f("ix_budgeted_expenses_category_id"))

    op.drop_table("budgeted_expenses")
    with op.batch_alter_table("analysis_periods", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_periods_user_id"))

    op.drop_table("analysis_periods")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_accounts_owner_id"))

    op.drop_table("accounts")
    op.drop_table("vendors")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_parent_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
